### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by BaconErie** [BaconErie/SnapTo#2]
- [x] Edit all emit on the server-side to not send objects
- [x] Finish client-side select answer
- [x] Finish client-side display answer checking
- [ ] Finish client-side leaderboard
- [ ] Finish host
- [ ] Finish answer terms json thingy
